// Generated by CoffeeScript 1.7.1
var App;

App = (function() {
  var methods, registerEvents;
  registerEvents = function() {
    var restartButton;
    restartButton = document.querySelector(".restart-button");
    return restartButton.addEventListener("click", function(e) {
      e.preventDefault();
      e.stopPropagation();
      return methods.restart();
    });
  };
  return methods = {
    init: function() {
      new Game("You", ["Kio", "Neo", "Danke", "Kawita"]);
      return registerEvents();
    },
    restart: function() {
      return window.location.reload();
    }
  };
})();

App.init();

//# sourceMappingURL=app.map
