// Generated by CoffeeScript 1.7.1
var Attack;

Attack = (function() {
  function Attack(source, target) {
    this.source = source;
    this.target = target;
    this.fire();
  }

  Attack.prototype.fire = function(type) {
    this.dom = document.createElement("div");
    this.dom.className = "attack";
    if (type != null) {
      this.dom.className += " " + type;
    }
    this.dom.style.webkitTransform = "translate(" + this.source.x + "px, " + this.source.y + "px)";
    document.body.appendChild(this.dom);
    return requestAnimationFrame((function(_this) {
      return function() {
        _this.dom.style.webkitTransform = "translate(" + _this.target.x + "px, " + _this.target.y + "px)";
        return setTimeout(function() {
          return _this.destroy();
        }, 1500);
      };
    })(this));
  };

  Attack.prototype.destroy = function() {
    return this.dom.remove();
  };

  return Attack;

})();

//# sourceMappingURL=attack.map
