// Generated by CoffeeScript 1.7.1
var Enemy;

Enemy = (function() {
  var randomPosition;

  randomPosition = function() {
    var maxHeight, maxWidth, minWidth;
    maxWidth = window.innerWidth - 100;
    minWidth = maxWidth - (maxWidth / 3);
    maxHeight = window.innerHeight - 100;
    return {
      x: Math.floor(Math.random() * (maxWidth - minWidth + 1) + minWidth),
      y: Math.floor(Math.random() * (maxHeight - 50 + 1) + 50)
    };
  };

  function Enemy(name) {
    this.name = name;
    this.position = randomPosition();
    this.alive = true;
    this.spawn();
  }

  Enemy.prototype.spawn = function() {
    this.dom = document.createElement("div");
    this.dom.className = "enemy";
    this.dom.dataset.name = this.name;
    this.dom.style.webkitTransform = "translate(" + this.position.x + "px, " + this.position.y + "px)";
    document.body.appendChild(this.dom);
    return this.registerEvents();
  };

  Enemy.prototype.registerEvents = function() {
    return this.dom.addEventListener("click", (function(_this) {
      return function(e) {
        return setTimeout(function() {
          return _this.die();
        }, 1500);
      };
    })(this));
  };

  Enemy.prototype.die = function() {
    this.alive = false;
    return this.dom.remove();
  };

  return Enemy;

})();

//# sourceMappingURL=enemy.map
