// Generated by CoffeeScript 1.7.1
var Fireball,
  __hasProp = {}.hasOwnProperty,
  __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

Fireball = (function(_super) {
  __extends(Fireball, _super);

  function Fireball() {
    return Fireball.__super__.constructor.apply(this, arguments);
  }

  Fireball.prototype.fire = function() {
    return Fireball.__super__.fire.call(this, "fireball");
  };

  return Fireball;

})(Attack);

//# sourceMappingURL=fireball.map
