// Generated by CoffeeScript 1.7.1
var Game;

Game = (function() {
  function Game(player, enemies) {
    var enemy;
    this.player = new Player(player);
    this.enemies = (function() {
      var _i, _len, _results;
      _results = [];
      for (_i = 0, _len = enemies.length; _i < _len; _i++) {
        enemy = enemies[_i];
        _results.push(new Enemy(enemy));
      }
      return _results;
    })();
  }

  return Game;

})();

//# sourceMappingURL=game.map
