// Generated by CoffeeScript 1.7.1
var Player;

Player = (function() {
  function Player(name) {
    this.name = name;
    this.score = 0;
    this.bullets = 30;
    this.position = {
      x: 100,
      y: window.innerHeight - 100
    };
    this.spawn();
  }

  Player.prototype.spawn = function() {
    this.dom = document.createElement("div");
    this.dom.className = "player";
    this.dom.dataset.name = this.name;
    this.dom.style.webkitTransform = "translate(" + this.position.x + "px, " + this.position.y + "px)";
    document.body.appendChild(this.dom);
    return this.registerEvents();
  };

  Player.prototype.registerEvents = function() {
    document.addEventListener("click", (function(_this) {
      return function(e) {
        return _this.attack({
          x: e.layerX,
          y: e.layerY
        });
      };
    })(this));
    return document.addEventListener("keydown", (function(_this) {
      return function(e) {
        if (e.which === 38 && _this.position.y > 30) {
          return _this.move(-30);
        } else if (e.which === 40 && _this.position.y < window.innerHeight - 100) {
          return _this.move(30);
        }
      };
    })(this));
  };

  Player.prototype.move = function(amount) {
    this.position.y += amount;
    return this.dom.style.webkitTransform = "translate(" + this.position.x + "px, " + this.position.y + "px)";
  };

  Player.prototype.attack = function(target) {
    if (this.bullets && --this.bullets) {
      return new Fireball(this.position, target);
    }
  };

  return Player;

})();

//# sourceMappingURL=player.map
